# Generated by Django 6.0.1 on 2026-02-03 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepticareApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reptile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reptile_name', models.CharField(max_length=30, verbose_name='reptiles name')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RepticareApp.profile')),
            ],
        ),
    ]
