# Generated by Django 6.0.1 on 2026-02-03 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepticareApp', '0002_reptile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reptile',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='reptile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='RepticareApp.reptile'),
        ),
    ]
