# Generated by Django 6.0.1 on 2026-02-03 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepticareApp', '0003_remove_reptile_profile_profile_reptile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='reptile',
        ),
        migrations.AddField(
            model_name='reptile',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reptiles', to='RepticareApp.profile'),
        ),
    ]
