# Generated by Django 6.0.1 on 2026-02-03 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepticareApp', '0004_remove_profile_reptile_reptile_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reptile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reptiles', to='RepticareApp.profile'),
        ),
    ]
