# Generated by Django 6.0.1 on 2026-02-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepticareApp', '0005_alter_reptile_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='reptile',
            name='reptile_species',
            field=models.CharField(max_length=60, null=True, verbose_name='reptile_species'),
        ),
        migrations.AlterField(
            model_name='reptile',
            name='reptile_name',
            field=models.CharField(max_length=30, verbose_name='reptile name'),
        ),
    ]
