# Generated by Django 6.0.1 on 2026-02-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepticareApp', '0006_reptile_reptile_species_alter_reptile_reptile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reptile',
            name='reptile_species',
            field=models.CharField(max_length=60, verbose_name='reptile_species'),
        ),
    ]
