# Generated by Django 6.0.1 on 2026-02-07 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepticareApp', '0007_alter_reptile_reptile_species'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeederType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('species', models.CharField(blank=True, max_length=60)),
                ('default_unit', models.CharField(choices=[('count', 'Count'), ('g', 'Grams')], max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='reptile',
            name='estimated_age_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reptile',
            name='estimated_age_record_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FeedLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fed_on', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('feeder', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='RepticareApp.feedertype')),
                ('reptile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedings', to='RepticareApp.reptile')),
            ],
        ),
        migrations.CreateModel(
            name='Terrarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terrarium_nickname', models.CharField(max_length=30, verbose_name='terrarium_nickname')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terrariums', to='RepticareApp.profile')),
                ('reptile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='terrarium', to='RepticareApp.reptile')),
            ],
        ),
        migrations.CreateModel(
            name='TerrariumLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_temp', models.IntegerField(blank=True, null=True)),
                ('lowest_temp', models.IntegerField(blank=True, null=True)),
                ('highest_humidity', models.IntegerField(blank=True, null=True)),
                ('lowest_humidity', models.IntegerField(blank=True, null=True)),
                ('date_recorded', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('terrarium', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enviroment_logs', to='RepticareApp.terrarium')),
            ],
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('notes', models.TextField(blank=True)),
                ('recorded_on', models.DateField(auto_now_add=True)),
                ('reptile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weights', to='RepticareApp.reptile')),
            ],
        ),
    ]
