# Generated by Django 6.0.1 on 2026-02-07 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepticareApp', '0008_feedertype_reptile_estimated_age_months_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reptile',
            name='estimated_age_months',
            field=models.IntegerField(blank=True, null=True, verbose_name='reptile_estimated_age'),
        ),
        migrations.AlterField(
            model_name='reptile',
            name='estimated_age_record_date',
            field=models.DateField(blank=True, null=True, verbose_name='reptile_age_record_date'),
        ),
    ]
