# Generated by Django 6.0.1 on 2026-02-16 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RepticareApp', '0009_alter_reptile_estimated_age_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedertype',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeders', to='RepticareApp.profile'),
        ),
    ]
